print("Hello World")
print("Jatin Katyal")
print(1)
print(1 , 2 , 3 , 4 , "jatin" , 3.4 , 1+5j)
print("Hello")
print("World !")
print("Hello" , end = " , ")
print("world !")

print("Hello" , end =" / ")
print("world !")
print(1 , 2 , 3 , 4 ,"jatina",3.4 , 1+5j, sep=",")
print("a")
print("b")
print("c")

print('a',end=" , ")
print('b' , end="#")
print('c')